input_directory: "../input"
output_directory: "../output"
move_files: false
image_extensions:
  - 'jpg'
  - 'jpeg'
  - 'png'
  - '.bmp'
  - '.gif'
logging_level: "INFO"
tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
num_cores: 7
number_of_class_to_predict: 3
validation_conditions:
  text_threshold: 300
  blurriness_threshold: 2000
  white_percentage_threshold: 25
  trash_classes:
    - "menu"
    - "web site"
    - "envelope"