input_directory: "../input"
output_directory: "../output"
logging_level: "INFO"
tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
enrichment_num_cores: 4
analysis_blurriness_threshold: 100
