input_directory: "../input"
output_directory: "../output"
move_files: false
image_extensions:
  - 'jpg'
  - 'jpeg'
  - 'png'
  - '.bmp'
  - '.gif'
logging_level: "DEBUG"
tesseract_path: "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"
num_cores: 7
predictions_number: 3
sort_conditions:
  text_threshold: 0
  blurriness_threshold: 80
  white_percentage_threshold: 25
  trash_classes:
    - "menu"
    - "web site"
    - "envelope"